services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: goprocess
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cmd/main/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d goprocess"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: ./cmd/main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CRAWL_DB_URL: "postgres://user:pass@host.docker.internal:5432/mydb"
      PROCESS_DB_URL: "postgres://user:pass@postgres:5432/goprocess"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
